layout_spectrum: 0.4033297
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.9907251
  brandStrength: 0.5118152
  lightness: 0.801855
  brandColors:
    - '#FCCEA4'
    - '#D78939'
    - '#5C3021'
    - '#E9E9E0'
    - '#AAB6BB'
  rhythmicContrast: 0.6922429
typography_spectrum: 0.3819562
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Jorivian
