name: Jorivian
favicon: null
layout_spectrum: 0.3765566621441394
typography_spectrum: 0.8334684078581631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.021463324781507254
  lightness: 0.25873759808018804
  saturation: 0.7432301926892251
  rhythmicContrast: 0.024346949299797416
purpose: []
